# Generated by Django 4.2.5 on 2023-09-06 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tareas', '0002_alter_registrotareas_id_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotareas',
            name='asignada_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Asignada a'),
        ),
    ]
