# Generated by Django 4.2.5 on 2023-09-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotareas',
            name='prioridad',
            field=models.CharField(choices=[('1', 'Alta'), ('2', 'Baja')], default='1', max_length=1, verbose_name='Prioridad tarea'),
        ),
    ]
